@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.bonker.swordinthestone.server.attachment;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;