@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.bonker.swordinthestone.util;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;